import 'package:uuid/uuid.dart';
import '../../models/models.dart';

class SeedData {
  static final _uuid = const Uuid();

  static List<FoodItem> get initialFoods => [
        FoodItem(
          id: _uuid.v4(),
          name: 'Oatmeal',
          calories: 150,
          protein: 5,
          carbs: 27,
          fat: 3,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Breakfast',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Banana',
          calories: 89,
          protein: 1.1,
          carbs: 23,
          fat: 0.3,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Fruit',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Chicken Breast (Grilled)',
          calories: 165,
          protein: 31,
          carbs: 0,
          fat: 3.6,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Protein',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Brown Rice',
          calories: 111,
          protein: 2.6,
          carbs: 23,
          fat: 0.9,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Carbs',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Egg (Boiled)',
          calories: 155,
          protein: 13,
          carbs: 1.1,
          fat: 11,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Protein',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Apple',
          calories: 52,
          protein: 0.3,
          carbs: 14,
          fat: 0.2,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Fruit',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Greek Yogurt',
          calories: 59,
          protein: 10,
          carbs: 3.6,
          fat: 0.4,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Dairy',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Almonds',
          calories: 579,
          protein: 21,
          carbs: 22,
          fat: 50,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Nuts',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Paneer (Tikka)',
          calories: 265,
          protein: 18,
          carbs: 4,
          fat: 20,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Indian',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Roti (Whole Wheat)',
          calories: 120,
          protein: 3.5,
          carbs: 24,
          fat: 0.5,
          servingSize: 1,
          servingUnit: 'piece',
          category: 'Indian',
        ),
        FoodItem(
          id: _uuid.v4(),
          name: 'Dal Tadka',
          calories: 150,
          protein: 7,
          carbs: 20,
          fat: 5,
          servingSize: 100,
          servingUnit: 'g',
          category: 'Indian',
        ),
      ];
}
