import '../../models/models.dart';

class SeedData {
  static final List<FoodItem> initialFoods = [
    FoodItem(
      id: '1',
      name: 'Basmati Rice',
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      servingSize: 100,
      servingUnit: 'g',
      category: 'Grains',
    ),
    FoodItem(
      id: '2',
      name: 'Broccoli',
      calories: 34,
      protein: 2.8,
      carbs: 7,
      fat: 0.4,
      servingSize: 100,
      servingUnit: 'g',
      category: 'Vegetables',
    ),
    FoodItem(
      id: '3',
      name: 'Boiled Egg',
      calories: 77,
      protein: 6.3,
      carbs: 0.6,
      fat: 5.3,
      servingSize: 1,
      servingUnit: 'piece',
      category: 'Protein',
    ),
    FoodItem(
      id: '4',
      name: 'Greek Yogurt',
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fat: 0.4,
      servingSize: 100,
      servingUnit: 'g',
      category: 'Dairy',
    ),
    FoodItem(
      id: '5',
      name: 'Whole Milk',
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fat: 3.3,
      servingSize: 100,
      servingUnit: 'ml',
      category: 'Dairy',
    ),
    FoodItem(
      id: '6',
      name: 'Oats',
      calories: 389,
      protein: 16.9,
      carbs: 66,
      fat: 6.9,
      servingSize: 100,
      servingUnit: 'g',
      category: 'Grains',
    ),
    FoodItem(
      id: '7',
      name: 'Banana',
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      servingSize: 1,
      servingUnit: 'piece',
      category: 'Fruit',
    ),
  ];
}
